### ISSUE TITLE
It open normal among us, and not the anonym imposter one.

### ISSUE THREAD

**Issue by thetof91** [Wunax/among-us-anonymous-impostors-mod#2]
Hello.

I have made a copy of Among us folder. Copied in BepInEx 5.4.5 32 bit. And then the AnonymousImpostorsMod. But when I try to open Among us, it open I see innersloth logo, then it close down and open among us up again, but it opens up the normal among us instead of.

I have it "E:\Steam\steamapps\common\Among Us Anonym imposter\Among Us.exe". Have not had this problem with other mods, but this is first mod I see where have to use Bepinex.

**Comment by wunax** [comment]
Hello,

Saving the folder is only useful if there is a problem with the steam version. You can't even launch Among us from the backup folder, because steam will try to launch it from the installation directory (that's why Among us closes and then reopens the version from the steam installation directory).

Try to put the mod in the steam installation directory. You can remove the mod at any time by removing the `Among Us\BepInEx\plugins\AnonymousImpostorsMod.dll` file. 
Let me know if it worked.

**Comment by thetof91** [comment]
The same thing happen when do it like that. When open it crash and open new game. Then go create game, but can't see the option to turn anonym on.
The Bepinex I have download this one: https://i.imgur.com/0JrEEZK.png

**Comment by wunax** [comment]
Yes it's the right version of BepInEx.
Try to install the Microsoft Visual C++ Runtime x86 : https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by thetof91** [comment]
Now it works. Now I an see the option.

Notice a bug with option menu. When I open option and turn it on. Then close option and open it again, it is gone. Looks like this: https://i.imgur.com/dkQWzo4.png 
Nothing happen when check uncheck them, But it still work with typing in chat to turn off/on. 

Can first test ingame later when have some friends online. :)

**Comment by wunax** [comment]
Yes I'm aware of this bug, it appears sometimes when you reopen the settings menu, try to close and reopen the settings menu or use the chat for the moment, I'll try to fix it soon. 
I close the issue, re-open one if you encounter another problem.
