### ISSUE TITLE
kill eachother not working?

### ISSUE THREAD

**Issue by xMinamimoto** [Wunax/among-us-anonymous-impostors-mod#3]
We played the mod but sadly it's not possible for the imposters to kill eachother. We installed the latest mod, game & BepInEx Unity IL2CPP. When trying to kill an imposter nothing happens, making clear who's the other one. Also when choosing Solo Mode it's game breaking if at least two imposters are the only ones still alive. Did we miss something or is it a bug and if the latter, is it already known?

**Comment by wunax** [comment]
Sorry to hear that, these bugs are not supposed to happen. I'll need some more information.
- Does everyone have the mod installed? To be sure you should see in the main menu below the version of Among us, the line "Anonymous Impostors mod loaded", like this:
<img src="https://i.imgur.com/farwcLM.png" width="400">

- During the scene of introduction of the roles or during the game, do the impostors see their allies?
- What do you mean nothing happens when you try to kill another impostor? The kill button is not available? The player doesn't get killed?

**Comment by xMinamimoto** [comment]
Thanks for quick reply!
Yes, everyone installed correctly, we double checked that. Imposter allies are not visible too and the kill button still appears. Only the killing itself isn't triggered at all when clicking the button.

**Comment by BeeeVeee** [comment]
My friends and I had the exact same issue.  

Everyone installed correctly, as verified with screen share.  The impostors could not see their allies, however when they try to kill someone who happens to be the other impostor, the kill button appears but will not do anything when pressed.

**Comment by wunax** [comment]
It's very weird, I can't reproduce the issue. On which servers did you play?

**Comment by xMinamimoto** [comment]
We fixed the problem. Apparently VSync has to be on for the killing to be working. Without VSync killing with Q was possible, but not via button press.

**Comment by wunax** [comment]
Wow I just tested and indeed without VSync the button doesn't work when you want to kill another impostor. I never would have thought it was from the VSync. Thanks for the details, I'll try to see if a fix is possible.

**Comment by wunax** [comment]
The issue is normally solved with the [latest](https://github.com/Wunax/Among-Us-Anonymous-Impostors-Mod/releases/tag/v1.3) version 1.3. Thank you for your contribution, reopen another issue if you encounter another problem.
